---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:Jmcglobal/argocd-nginx-prvate.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"