---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:Jmcglobal/argocd-nginx.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACC4jkW4iz4FQqv6m6PEq7Cyh3n4arsJguE0ifOyU2EygQAAAKCpmyoEqZsq
    BAAAAAtzc2gtZWQyNTUxOQAAACC4jkW4iz4FQqv6m6PEq7Cyh3n4arsJguE0ifOyU2EygQ
    AAAECpL1gl2PR2CT1YraqpFvyUOmQ5MGalYIP34FUo5WFkjriORbiLPgVCq/qbo8SrsLKH
    efhquwmC4TSJ87JTYTKBAAAAHW1hY3Byb0BNYWNzLU1hY0Jvb2stUHJvLmxvY2Fs
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"