---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app2
  namespace: foo
  labels:
    app: nginx-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app2
  template:
    metadata:
      labels:
        app: nginx-app2
    spec:
      containers:
        - name: nginx
          image: jmcglobal/nginx:v0.2.2
          ports:
            - containerPort: 80