---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-1
  namespace: dev
  labels:
    app: nginx-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-1
  template:
    metadata:
      labels:
        app: nginx-app-1
    spec:
      containers:
        - name: nginx
          image: jmcglobal/nginx:v0.1.1
          ports:
            - containerPort: 80